import pyodbc
print("Connecting...")
conn = pyodbc.connect("DSN=Altibase ODBC Driver;UID=sys;PWD=manager;")
print("Executing query...")
cursor = conn.cursor()
cursor.execute("SELECT 'capture_test' FROM DUAL")
result = cursor.fetchone()
print(f"Result: {result[0]}")
conn.close()
print("Done!")